/*
    ;;;;;;;;;;;;;; to load external script copy the script in the directory as same name;;;;;;;;;;;;;;;;;;;;;;;;;; 
    ;;;;;;;;;;;;;; or change script source in EDITOR.html ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
				for error free access use loader application
    ** change var Json for loading files**
    (for external files give full path name)
        BANNER-TOP      => path of image will be used for banner on top
        BANNER-BOTTOM   => path of image will be used for banner on top
        VIDEO           => path of video file will be used 
        IMAGE           => path of multiple images will be used in 
                            (write under square brackets separate with ',')
        IMAGE_iD        => a string would be used as a id for every image with a index value
                               (any name)
        DATASCRIPT-NAME => name of the script using for the file
                                (must be unique for unique scripts)
            
                    **change var SyncImV for video and image syncronization**  
                        (replace from the file generated by the editor)
        IMAGE_ID      => image id s that are related with video timestamps
        VIDEO_TIME    => video timestamps
*/
///////////////////////   MEDIA DESCRIPTIONS   /////////////////////////////////////

Json["DATASCRIPT-NAME"] = ""
Json["BANNER-TOP"]      = "";
Json["BANNER-BOTTOM"]   = "";
Json["VIDEO"]           = "";
Json["VIDEO-POSTER"]    = "";
Json["IMAGE_id"]        = "";
Json["IMAGE"]           = [];

/////////////////////////    FUNCTIONAL DESCRIPTIONS   ////////////////////////////

SyncImV["IMAGE_ID"]     = [];
SyncImV["VIDEO_TIME"]   = [];

QuickView["FROM-TIME"]  = [[]];
QuickView["TO-TIME"]    = [[]];

///////////////////////////////////////////////////////////////
